# Header
menu:
  ğŸ   Home: /
  ğŸ“–  Archives: /archives
  ğŸ™ˆ  Friends: /friends
  ğŸ“·  Photos: /photos
  ğŸ‘´  About Me: /about
rss: /atom.xml

# Content
excerpt_link: é˜…è¯»å…¨æ–‡
fancybox: true
# Blogger
avatar: https://i.loli.net/2020/04/02/vl5RntXL8VDTu9x.jpg
introduce: é£æµªæ²¡å¹³æ¯ï¼Œæˆ‘å®£å‘Šå¥”è·‘çš„æ„ä¹‰
followurl: https://github.com/bochili
# Sidebar
sidebar: left
widgets:
- blogger
- blog_info
- tag
drawerwidgets:
- blogger
- navlist
- blog_info

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
