# Header
menu:
  ğŸ   Home: /
  ğŸ“–  Archives: /archives
  ğŸ™ˆ  Friends: /friends
  ğŸ“·  Photos: /photos
  ğŸ‘´  About Me: /about
rss: /atom.xml

#Theme
theme_color: o-apple

#Navbar
nav_fixed: true

# Content
excerpt_link: é˜…è¯»å…¨æ–‡
excerpt_link_shape: oval
excerpt_link_shadow: true
fancybox: true
# Blogger
avatar: https://i.loli.net/2020/07/13/3ltrdaZpvzMJUXR.jpg
introduce: é£æµªæ²¡å¹³æ¯ï¼Œæˆ‘å®£å‘Šå¥”è·‘çš„æ„ä¹‰
followurl: https://github.com/bochili
avatarjumpurl: https://www.wanan.run/
# Sidebar
sidebar: left
widgets:
- blogger
- theme
- blog_info
- tagcloud
drawerwidgets:
- blogger
- theme
- navlist

#Baidu Search Resource Platform
baidu_search:
  enable: false
  baidu_site_verification: O0eImcpYTc

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png

#Valine
valine:
  enable: false
  AppId: IOQF7YODEcwaCGUYxRXQQtUA-gzGzoHsz
  AppKey: C1pfrlS3mX2BFU8maxcpI5zv
  
#Google AdSense
AdSense:
  enable: false
  adclient: ca-pub-4994376664948778